=== n3hx/Information-in-Organisation/bookshop.dtd
<!ELEMENT bookshop (book*)> <!-- The booshop can have zero to many books in its store -->

<!ELEMENT book (ID, title, price?, author+, description, publisher?, genre?, edition+, availability?, cover_url)>

<!ELEMENT cover_url (#PCDATA)> <!-- cover_url is defined without URL -->

<!ELEMENT ID (#PCDATA)> <!--ID is defined without qualifier, because it occurs exactly once within the "book" element-->

<!ELEMENT title (#PCDATA)> <!--Title is defined without qualifier, because it occurs exactly once within the "book" element.-->

<!ELEMENT price (#PCDATA)> <!-- The book may have 1 or zero price attached to it(e.g out of stock = zero) -->

<!ELEMENT author (#PCDATA)> <!-- The book may have 1 to many autors -->

<!ELEMENT description (#PCDATA)> <!--Description is defined without qualifier, because it occurs exactly once within the "book" element.-->

<!ELEMENT publisher (#PCDATA)> <!-- The book may have 1 or zero publisher-->

<!ELEMENT genre (#PCDATA)>  <!-- The book may have 1 or zero genre-->

<!ELEMENT edition (#PCDATA)>  <!-- The book may have 1 to many edition-->

<!ELEMENT availability (#PCDATA)>  <!-- The book may have 1 or zero availability-->

=== n3hx/Information-in-Organisation/bookshop.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bookshop.xsl"?>
<!DOCTYPE bookshop SYSTEM "bookshop.dtd"> <!--Import set of rules from bookshop.dtd-->

<bookshop>
  <book>
    <cover_url>https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/After_2014_novel_cover.jpg/220px-After_2014_novel_cover.jpg</cover_url>
    <ID>1</ID>
    <title>After</title>
    <price> 500</price>
    <author>Anna Todd</author>
    <description>
      Once she meets Hardin, good girl Tessa’s life will never be the same. He is rude, cocky, and the exact opposite of her reliable boyfriend back home—she should hate him, but then she finds herself alone with him one night. What follows is a passionate but tempestuous romance that turns Tessa’s usually calm and traditional world upside down.
    </description>
    <publisher>New York Times bestselling author and Wattpad sensation Anna Todd</publisher>
    <genre>Romance</genre>
    <edition>1st Edition</edition>
    <availability>7</availability>
  </book>
  <book>
    <cover_url>https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781476792491/after-we-collided-9781476792491_hr.jpg</cover_url>
    <ID>2</ID>
    <title>After We Collided</title>
    <price> 550</price>
    <author>Anna Todd</author>
    <description>
      Tessa and Hardin’s tentative relationship takes a devastating turn when a dark secret from Hardin’s mysterious past surfaces. Can Tessa manage to move on and forge a new life for herself? Or will Hardin be able to change enough to win back his one true love?
    </description>
    <publisher>New York Times bestselling author and Wattpad sensation Anna Todd</publisher>
    <genre>Romance</genre>
    <edition>1st Edition</edition>
    <availability>4</availability>
  </book>
  <book>
    <cover_url>https://m.media-amazon.com/images/M/MV5BMTEzN2MxZWUtYTJkYS00NjU5LTk0ZjgtNzc1OTMwNWNjZGFkXkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_FMjpg_UX1000_.jpg</cover_url>
    <ID>3</ID>
    <title>After We Fell</title>
    <price> 600</price>
    <author>Anna Todd</author>
    <description>
      Hardin isn’t the only one with secrets. Everything Tessa thought she knew about her life goes up in smoke and she has no idea if Hardin will be willing to stay with her. Trapped in a seemingly unending cycle of jealousy and rage, neither has any idea if their passion is enough to keep their relationship alive.
    </description>
    <publisher>New York Times bestselling author and Wattpad sensation Anna Todd</publisher>
    <genre>Romance</genre>
    <edition>1st Edition</edition>
    <availability>13</availability>
  </book>
  <book>
    <cover_url>https://upload.wikimedia.org/wikipedia/en/thumb/6/63/AfterEverHappy.jpg/220px-AfterEverHappy.jpg</cover_url>
    <ID>4</ID>
    <title>After Ever Happy</title>
    <price> 550</price>
    <author>Anna Todd</author>
    <description>
      Each new challenge Tessa and Hardin face only makes their passionate bond stronger and stronger. But when a revelation about the past shakes Hardin’s impenetrable façade to the core—and then Tessa suffers a tragedy—will they stick together again or be torn apart?
    </description>
    <publisher>New York Times bestselling author and Wattpad sensation Anna Todd</publisher>
    <genre>Romance</genre>
    <edition>1st Edition</edition>
    <availability>8</availability>
  </book>
  <book>
    <cover_url>https://img.wattpad.com/cover/11596691-352-k938767.jpg</cover_url>
    <ID>5</ID>
    <title>Before</title>
    <price>280</price>
    <author>Anna Todd</author>
    <description>The ups and downs of Tessa and Hardin’s relationship are explored by others in their lives before, during, and after the events of the series. Finally, Hardin reveals his own perception of his life with Tessa, which will completely change how you see the famous brooding boy and the angel who loved him.</description>
    <publisher>New York Times bestselling author and Wattpad sensation Anna Todd</publisher>
    <genre>Romance</genre>
    <edition>1st</edition>
    <availability>0</availability>
  </book>
  <book>
    <cover_url>https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1610900883i/54189398.jpg</cover_url>
    <ID>6</ID>
    <title>The Spanish Love Deception</title>
    <price>600</price>
    <author>Elisabeth LaBan</author>
    <description>
      From the author of the Goodreads Choice Award winner The Spanish Love Deception, the eagerly anticipated follow-up featuring Rosie Graham and Lucas Martín, who are forced to share a New York apartment.
    </description>
    <publisher>Goodreads</publisher>
    <genre>Romance</genre>
    <edition>1st Edition</edition>
    <availability>9</availability>
  </book>
  <book>
    <cover_url>https://upload.wikimedia.org/wikipedia/en/a/a9/The_Fault_in_Our_Stars.jpg</cover_url>
    <ID>7</ID>
    <title>The Fault in Our Stars</title>
    <price> 500</price>
    <author>John Green</author>
    <description>
      Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis. But when a gorgeous plot twist named Augustus Waters suddenly appears at Cancer Kid Support Group, Hazel’s story is about to be completely rewritten.
    </description>
    <publisher>Penguin Books</publisher>
    <genre>Romance</genre>
    <edition>1st Edition</edition>
    <availability>7</availability>
  </book>
  <book>
    <cover_url>https://m.media-amazon.com/images/I/81XS0eEa6dL._AC_UF1000,1000_QL80_.jpg</cover_url>
    <ID>8</ID>
    <title>Love on the brain</title>
    <price> 550</price>
    <author>Ali Hazelwood</author>
    <description>
      An Instant New York Times Bestseller. From the New York Times bestselling author of The Love Hypothesis comes a new STEMinist rom-com in which a scientist is forced to work on a project with her nemesis—with explosive results.
    </description>
    <publisher>Harper Collins</publisher>
    <genre>Romance</genre>
    <edition>1st Edition</edition>
    <availability>4</availability>
  </book>
  <book>
    <cover_url>https://shop.pbs.org/graphics/products/zoom/WE7522.jpg</cover_url> 
    <ID>21</ID>
    <title>History!</title>
    <price>750</price>
    <author>Smith Sonian</author>
    <description>Journey back in time and marvel at the history of our world like never before with this children's encyclopedia perfect for curious kids.</description>
    <publisher>DK Publishing</publisher>
    <genre>Children's Encyclopedia</genre>
    <edition>2nd Edition</edition>
    <availability>0</availability>
  </book>
  <book>
    <cover_url>https://m.media-amazon.com/images/I/A1ZzLLtfklL._AC_UF1000,1000_QL80_.jpg</cover_url>
    <ID>22</ID>
    <title>Great Maps</title>
    <price>600</price>
    <author>Smith Sonian</author>
    <description>A superbly illustrated guide to 64 maps from all around the world!</description>
    <publisher>DK Publishing</publisher>
    <genre>History</genre>
    <edition>1st Edition</edition>
    <availability>6</availability>
  </book>
  <book>
    <cover_url>https://m.media-amazon.com/images/I/A1un1wEhBmL._AC_UF894,1000_QL80_.jpg</cover_url>
    <ID>23</ID>
    <title>Battles That Changed History</title>
    <price>850</price>
    <author>DK Publishing</author>
    <description>From the fury of the Punic Wars to the icy waters of Dunkirk, relive 5,000 years of world-changing combat with this guide to the most famous battles in history.</description>
    <publisher>DK Publishing</publisher>
    <genre>Military History</genre>
    <edition>Revised Edition</edition>
    <availability>0</availability>
  </book>
  <book>
    <cover_url>https://m.media-amazon.com/images/I/31ktLD3IJnL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg</cover_url>
    <ID>24</ID>
    <title>Slavery: A World History</title>
    <price>450</price>
    <author>Milton Meltzer</author>
    <description>Slavery is not and has never been a "peculiar institution," but one that is deeply rooted in the history and economy of most countries.</description>
    <publisher>HarperCollins</publisher>
    <genre>History</genre>
    <edition>3rd Edition</edition>
    <availability>5</availability>
  </book>
  <book>
    <cover_url>https://www.jonathanball.co.za/images/stories/virtuemart/product/JB-Apartheid-2ndEd%20FC.jpg</cover_url>
    <ID>25</ID>
    <title>Apartheid: An Illustrated History</title>
    <price>550</price>
    <author>Michael Morris</author>
    <description>The one thing that looms largest in South Africa's future is South Africa's past – most especially the nearly five decades of division and conflict at the heart of one of the twentieth century's most infamous social experiments.</description>
    <publisher>Penguin Random House</publisher>
    <genre>History</genre>
    <edition>1st Edition</edition>
    <availability>3</availability>
  </book>
  <book>
    <cover_url>https://m.media-amazon.com/images/I/71Jc44eqJCL._AC_UF1000,1000_QL80_.jpg</cover_url>
    <ID>28</ID>
    <title>French Revolution</title>
    <price>300</price>
    <author>Hourly History</author>
    <description>During the late years of the 18th century, the spirit of Enlightenment thinking and revolution were in the air. The world was changing, moving away from ingrained beliefs about religion, reason, society, and the rights of the individual and turning more toward the laws of nature as interpreted by the scientific method. Nowhere was the influence of this radical new way of thinking more apparent than in France, and the upheaval this caused would come to bloody fruition in the form of revolution.</description>
    <publisher>Hourly History</publisher>
    <genre>History</genre>
    <edition>1st Edition</edition>
    <availability>6</availability>
  </book>
  <book>
